name: Build Appliances
on:
  repository_dispatch:
    types:
    - build
  workflow_dispatch:
jobs:
  setup:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        repository: bdunne/manageiq-appliance-build
        ref: actions_appliance_build
    - name: Clone Imagefactory
      run: |
        git clone https://www.github.com/bdunne/imagefactory.git /build/gha/$GITHUB_RUN_ID/imagefactory
