name: Build Appliances
on:
  repository_dispatch:
    types:
    - build
  workflow_dispatch:
jobs:
  setup:
    runs-on: self-hosted
    steps:
    - name: Clone Imagefactory
      run: |
        git clone https://www.github.com/bdunne/imagefactory.git /build/gha/$GITHUB_RUN_ID/imagefactory
  build_appliances:
    strategy:
      max-parallel: 2
      matrix:
        target: [azure, libvirt]
    runs-on: self-hosted
    needs: setup
    env:
      TARGET_PLATFORM: ${{ matrix.target }}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: bdunne/manageiq-appliance-build
        ref: actions_appliance_build
    - name: Build appliance images
      env:
        IBM_CLOUD_ACCESS_KEY: ${{ secrets.IBM_CLOUD_ACCESS_KEY }}
        IBM_CLOUD_ENDPOINT: ${{ secrets.IBM_CLOUD_ENDPOINT }}
        IBM_CLOUD_SECRET_KEY: ${{ secrets.IBM_CLOUD_SECRET_KEY }}
      run: "ruby scripts/vmbuild.rb --type nightly --reference $GITHUB_REF_NAME --copy-dir $GITHUB_REF_NAME --only $TARGET_PLATFORM --upload --delete | tee -a /build/logs/${GITHUB_REF_NAME}_$(date +'%Y%m%d')_${GITHUB_RUN_ID}.log"
