name: Build Appliances
on:
  repository_dispatch:
    types:
    - build
  workflow_dispatch:
jobs:
  build_appliances:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        repository: bdunne/manageiq-appliance-build
        ref: actions_appliance_build
    - name: Clone Imagefactory
      run: |
        git clone https://www.github.com/bdunne/imagefactory.git /build/gha/$GITHUB_RUN_ID/imagefactory
        # pushd /build/gha/$GITHUB_RUN_ID/imagefactory/scripts/
        # ./imagefactory_dev_setup.sh
        # popd
    - name: Build pods containers
      run: ruby scripts/vmbuild.rb --type nightly --upload --reference master --copy-dir master
