name: Build Appliances
on:
  repository_dispatch:
    types:
    - build
  workflow_dispatch:
jobs:
  setup:
    runs-on: self-hosted
    steps:
    - name: Clone Imagefactory
      run: |
        git clone https://www.github.com/bdunne/imagefactory.git /build/gha/$GITHUB_RUN_ID/imagefactory
  build_appliances:
    strategy:
      max-parallel: 2
      matrix:
        target: [azure, libvirt]
    runs-on: self-hosted
    needs: setup
    env:
      TARGET_PLATFORM: ${{ matrix.target }}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: bdunne/manageiq-appliance-build
        ref: actions_appliance_build
    - name: Build appliance images
      run: "ruby scripts/vmbuild.rb --type nightly --reference $GITHUB_REF_NAME --copy-dir $GITHUB_REF_NAME --only $TARGET_PLATFORM"
  finalize:
    needs: build_appliances
    runs-on: self-hosted
    steps:
    - name: Upload
      run: "ruby scripts/vmbuild.rb --type nightly --reference $GITHUB_REF_NAME --copy-dir $GITHUB_REF_NAME --upload-only"
