---
name: CI
on:
  push:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run golang tests
      run: |
        echo 'cpuinfo'
        cat /proc/cpuinfo
        echo 'disk usage'
        df -h
        echo 'XXXXX WHOAMI'
        echo "ME $(whoami), $(groups)"
        echo 'XXXXX INSTALL'
        sudo apt -y install bridge-utils cpu-checker libvirt-clients libvirt-daemon qemu qemu-kvm
        echo 'XXXXX KVM-ok'
        kvm-ok
        echo 'XXXXX virt-host-validate'
        virt-host-validate
