---
name: CI
on:
  push:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
        - '2.7'
        - '3.0'
    steps:
    - uses: actions/checkout@v3
    - name: Run golang tests
      run: |
        echo 'cpuinfo'
        cat /proc/cpuinfo
        echo 'disk usage'
        df -h
